# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Engineering'
tagline:          'getting 1% better every day'
description:      'A place for <a href="http://www.betterworks.com">BetterWorks</a> engineers to geek out over all things interesting.'
url:              http://engineering.betterworks.com
baseurl:          /

author:
  name:           BetterWorks
  url:            http://www.betterworks.com

paginate:         5

github:
  repo:           https://github.com/betterworks/engineering
