# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BetterWorks Engineering Blog
tagline:          1% better every day
description:      A place for <a href="https://betterworks.com">BetterWorks</a> engineers to geek out over all things interesting.
url:              https://engineering.betterworks.com
baseurl:          /

author:
  name:           BetterWorks
  url:            https://betterworks.com

paginate:         5

github:
  repo:           https://github.com/betterworks/engineering
